$(function(){
$("#btn1").click(function(){
$("[id^=description1]").slideToggle();
});
});
$(function(){
$("#btn2").click(function(){
$("[class^=picture1]").slideToggle();
});
});
$(function(){
$("#btn2").click(function(){
$("[class^=picture2]").slideToggle();
});
});
$(function(){
$("#btn2").click(function(){
$("[class^=picture3]").slideToggle();
});
});
$(function(){
$("#btn2").click(function(){
$("[class^=picture4]").slideToggle();
});
});
$(function(){
$("#btn3").click(function(){
$("[class^=picture5]").slideToggle();
});
});